// app/modules/ui/elements.js
// Central repository for DOM element references.

export const elements = {
    loadFilesButton: document.getElementById('load-files-button'),
    toggleEditorButton: document.getElementById('toggle-editor-button'),
    saveProjectButton: document.getElementById('save-project'),
    exportProjectButton: document.getElementById('export-project'),
    importProjectInput: document.getElementById('import-project'),
    audioUpload: document.getElementById('audio-upload'),
    lyricsUpload: document.getElementById('lyrics-upload'),
    imageUpload: document.getElementById('image-upload'),
    projectNameInput: document.getElementById('project-name'),
    lyricsList: document.getElementById('lyrics-list'),
    songTitle: document.getElementById('song-title'),
    songImage: document.getElementById('song-image'),
    songImageContainer: document.getElementById('song-image-container'),
    loadingOverlay: document.getElementById('loading-overlay'),
    loadingMessage: document.getElementById('loading-message'),
    historyList: document.getElementById('history-list'),
    timingEditorDiv: document.getElementById('footer-timing-editor'),
    controlsContainer: document.getElementById('footer-controls'),
    playPauseButton: document.getElementById('play-pause'),
    prevSongButton: document.getElementById('prev-song'),
    nextSongButton: document.getElementById('next-song'),
    volumeSlider: document.getElementById('volume-slider'),
    progressBar: document.getElementById('progress-bar'),
    currentTimeLabel: document.getElementById('current-time'),
    durationLabel: document.getElementById('duration'),
    selectedLineStartLabel: document.getElementById('selected-line-start'),
    selectedLineEndLabel: document.getElementById('selected-line-end'),
    setLineStartButton: document.getElementById('set-line-start'),
    setLineEndButton: document.getElementById('set-line-end'),
    nudgeStartBackButton: document.getElementById('nudge-start-back'),
    nudgeStartForwardButton: document.getElementById('nudge-start-forward'),
    nudgeEndBackButton: document.getElementById('nudge-end-back'),
    nudgeEndForwardButton: document.getElementById('nudge-end-forward'),
    clearLineTimesButton: document.getElementById('clear-line-times'),
    lyricsContainer: document.querySelector('.lyrics-container'),
    colorBgInput: document.getElementById('color-bg'),
    colorTextInput: document.getElementById('color-text'),
    colorHighlightBgInput: document.getElementById('color-highlight-bg'),
    colorHighlightTextInput: document.getElementById('color-highlight-text'),
    footerContainer: document.getElementById('footer-root'),
    footerTimingEditor: document.getElementById('footer-timing-editor'),
    footerControls: document.getElementById('footer-controls'),
    sidebar: document.getElementById('sidebar'),
    sidebarToggle: document.getElementById('toggle-sidebar'),
    mainContentFrame: document.getElementById('main-content-frame'),
    // Add any new elements here
};